name = input("Enter name:")
collagename = input("Enter collage name:")
rollno = input("Enter roll no:")
add=input("Enter address:")
print("********** student details **********")
print(name)
print(collagename)
print(rollno)
print(add)
